flow:
  - ontologenius::ReasonerChain
  - ontologenius::ReasonerGeneralize
  - ontologenius::ReasonerDictionary
  - ontologenius::ReasonerInverseOf
  - ontologenius::ReasonerRangeDomain
  - ontologenius::ReasonerSymmetric
  - ontologenius::ReasonerAnonymous
  - ontologenius::ReasonerTransitivity
ontologenius::ReasonerGeneralize:
  min_count : 2
  min_percent : 0.7
ontologenius::ReasonerDictionary:
  use_id : true
ontologenius::ReasonerAnonymous:
  standard_mode : true
